<?php 

use Drupal\core\Form\FormStateInterface;


/* implementation of hook_form_alter */

function site_alter_form_alter(&$form, FormStateInterface $form_state, $form_id) {

	if($form_id == "system_site_information_settings"){


		/* getting API Key */

		$site_api_key = \Drupal::config('site_api_key.settings')->get('site_api_key');
		
		$form['site_information']['site_api_key'] = array(
			'#title' => 'Site API Key',
			'#type' => 'textfield',
			'#default_value' => $site_api_key,
		);

		if($site_api_key != "") {
			$form['actions']['submit']['#value'] = t('Update Configuration');
		}

		$form['#submit'][] = 'site_apikey_submit';
	}
 
}

/* store api key */

function site_apikey_submit(&$form, FormStateInterface $form_state) {

	 \Drupal::configFactory()->getEditable('site_api_key.settings')
	  ->set('site_api_key', $form_state->getValue('site_api_key'))
      ->save();

	drupal_set_message(t('Site API Key %string has been Saved.', array('%string' => $form_state->getValue('site_api_key'))));
}